services:
  - type: web
    name: galeria-titan
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app --workers 2 --threads 2 --timeout 180"
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: MAPILLARY_TOKEN
        sync: false
    healthCheckPath: "/"
    autoDeploy: true

